replicaCount: 1

image:
  repository: 9ilbert/member
  pullPolicy: Always
  tag: "amd-0.1"

application:
  profile: ''
  server:
    port: 8080

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

resources:
  limits:
    cpu: 1000m
    memory: 512Mi

rollout:
  strategy: bluegreen
  autoPromotionEnabled: true

hostName: msa.member.com

# livenessProbe:
#   httpGet:
#     path: /members
#     port: 8080
# readinessProbe:
#   httpGet:
#     path: /members
#     port: 8080

serviceAccount:
  annotations: {}

pinpoint:
  enabled: true
  version: 2.5.1
